# coding: utf-8

"""
    Paubox Email API

    Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paubox.api.messages_api import MessagesApi


class TestMessagesApi(unittest.TestCase):
    """MessagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessagesApi()

    def tearDown(self) -> None:
        pass

    def test_get_message_receipt(self) -> None:
        """Test case for get_message_receipt

        Get email disposition
        """
        pass

    def test_send_bulk_messages(self) -> None:
        """Test case for send_bulk_messages

        Send multiple email messages (batch)
        """
        pass

    def test_send_message(self) -> None:
        """Test case for send_message

        Send a single email message
        """
        pass


if __name__ == '__main__':
    unittest.main()
