# coding: utf-8

"""
    Paubox Email API

    Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paubox.models.templated_message_request_data import TemplatedMessageRequestData

class TestTemplatedMessageRequestData(unittest.TestCase):
    """TemplatedMessageRequestData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplatedMessageRequestData:
        """Test TemplatedMessageRequestData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplatedMessageRequestData`
        """
        model = TemplatedMessageRequestData()
        if include_optional:
            return TemplatedMessageRequestData(
                template_name = 'detailed_test',
                template_values = '{ "name": "Howard", "conditional":"true","items":["one","two","three"] }',
                message = paubox.models.templated_message.TemplatedMessage(
                    recipients = [
                        ''
                        ], 
                    bcc = [
                        ''
                        ], 
                    cc = [
                        ''
                        ], 
                    headers = paubox.models.templated_message_headers.TemplatedMessageHeaders(
                        subject = '', 
                        from = '', 
                        reply_to = '', 
                        list_unsubscribe = '', 
                        list_unsubscribe_post = '', 
                        additional_properties = '', ), 
                    allow_non_tls = True, 
                    force_secure_notification = True, 
                    attachments = [
                        paubox.models.attachment.Attachment(
                            file_name = '', 
                            content_type = '', 
                            content = '', )
                        ], )
            )
        else:
            return TemplatedMessageRequestData(
                template_name = 'detailed_test',
                template_values = '{ "name": "Howard", "conditional":"true","items":["one","two","three"] }',
                message = paubox.models.templated_message.TemplatedMessage(
                    recipients = [
                        ''
                        ], 
                    bcc = [
                        ''
                        ], 
                    cc = [
                        ''
                        ], 
                    headers = paubox.models.templated_message_headers.TemplatedMessageHeaders(
                        subject = '', 
                        from = '', 
                        reply_to = '', 
                        list_unsubscribe = '', 
                        list_unsubscribe_post = '', 
                        additional_properties = '', ), 
                    allow_non_tls = True, 
                    force_secure_notification = True, 
                    attachments = [
                        paubox.models.attachment.Attachment(
                            file_name = '', 
                            content_type = '', 
                            content = '', )
                        ], ),
        )
        """

    def testTemplatedMessageRequestData(self):
        """Test TemplatedMessageRequestData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
