# coding: utf-8

"""
    Paubox Email API

    Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paubox.models.bulk_send_request import BulkSendRequest

class TestBulkSendRequest(unittest.TestCase):
    """BulkSendRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkSendRequest:
        """Test BulkSendRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkSendRequest`
        """
        model = BulkSendRequest()
        if include_optional:
            return BulkSendRequest(
                data = paubox.models.bulk_send_request_data.BulkSendRequest_data(
                    messages = [
                        paubox.models.message.Message(
                            recipients = [
                                ''
                                ], 
                            bcc = [
                                ''
                                ], 
                            cc = [
                                ''
                                ], 
                            headers = paubox.models.message_headers.MessageHeaders(
                                subject = '', 
                                from = '', 
                                reply_to = '', 
                                list_unsubscribe = '', 
                                list_unsubscribe_post = '', 
                                x_custom_header = '', 
                                additional_properties = '', ), 
                            allow_non_tls = True, 
                            force_secure_notification = True, 
                            content = paubox.models.message_content.MessageContent(
                                text/plain = '', 
                                text/html = '', ), 
                            attachments = [
                                paubox.models.attachment.Attachment(
                                    file_name = '', 
                                    content_type = '', 
                                    content = '', )
                                ], )
                        ], )
            )
        else:
            return BulkSendRequest(
                data = paubox.models.bulk_send_request_data.BulkSendRequest_data(
                    messages = [
                        paubox.models.message.Message(
                            recipients = [
                                ''
                                ], 
                            bcc = [
                                ''
                                ], 
                            cc = [
                                ''
                                ], 
                            headers = paubox.models.message_headers.MessageHeaders(
                                subject = '', 
                                from = '', 
                                reply_to = '', 
                                list_unsubscribe = '', 
                                list_unsubscribe_post = '', 
                                x_custom_header = '', 
                                additional_properties = '', ), 
                            allow_non_tls = True, 
                            force_secure_notification = True, 
                            content = paubox.models.message_content.MessageContent(
                                text/plain = '', 
                                text/html = '', ), 
                            attachments = [
                                paubox.models.attachment.Attachment(
                                    file_name = '', 
                                    content_type = '', 
                                    content = '', )
                                ], )
                        ], ),
        )
        """

    def testBulkSendRequest(self):
        """Test BulkSendRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
