# coding: utf-8

"""
    Paubox Email API

    Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paubox.models.message_receipt_response import MessageReceiptResponse

class TestMessageReceiptResponse(unittest.TestCase):
    """MessageReceiptResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MessageReceiptResponse:
        """Test MessageReceiptResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MessageReceiptResponse`
        """
        model = MessageReceiptResponse()
        if include_optional:
            return MessageReceiptResponse(
                source_tracking_id = '6e1cf9a4-7bde-4834-8200-ed424b50c8a7',
                data = paubox.models.message_receipt_response_data.MessageReceiptResponse_data(
                    message = paubox.models.message_receipt_response_data_message.MessageReceiptResponse_data_message(
                        id = '<f4a9b518-439c-497d-b87f-dfc9cc19194b@authorized_domain.com>', 
                        message_deliveries = [
                            paubox.models.message_delivery.MessageDelivery(
                                recipient = 'recipient@host.com', 
                                status = paubox.models.delivery_status.DeliveryStatus(
                                    delivery_status = 'delivered', 
                                    delivery_time = 'Mon, 23 Apr 2018 13:27:34 -0700', 
                                    opened_status = 'opened', 
                                    opened_time = 'Mon, 23 Apr 2018 13:27:51 -0700', ), )
                            ], 
                        total_opens = 1, 
                        distinct_opens = 1, 
                        total_click_count = 2, 
                        clicks_per_link = [
                            paubox.models.click_data.ClickData(
                                click_count = 1, 
                                target_url = 'amazon.com', )
                            ], 
                        unsubscribed = False, ), )
            )
        else:
            return MessageReceiptResponse(
                source_tracking_id = '6e1cf9a4-7bde-4834-8200-ed424b50c8a7',
                data = paubox.models.message_receipt_response_data.MessageReceiptResponse_data(
                    message = paubox.models.message_receipt_response_data_message.MessageReceiptResponse_data_message(
                        id = '<f4a9b518-439c-497d-b87f-dfc9cc19194b@authorized_domain.com>', 
                        message_deliveries = [
                            paubox.models.message_delivery.MessageDelivery(
                                recipient = 'recipient@host.com', 
                                status = paubox.models.delivery_status.DeliveryStatus(
                                    delivery_status = 'delivered', 
                                    delivery_time = 'Mon, 23 Apr 2018 13:27:34 -0700', 
                                    opened_status = 'opened', 
                                    opened_time = 'Mon, 23 Apr 2018 13:27:51 -0700', ), )
                            ], 
                        total_opens = 1, 
                        distinct_opens = 1, 
                        total_click_count = 2, 
                        clicks_per_link = [
                            paubox.models.click_data.ClickData(
                                click_count = 1, 
                                target_url = 'amazon.com', )
                            ], 
                        unsubscribed = False, ), ),
        )
        """

    def testMessageReceiptResponse(self):
        """Test MessageReceiptResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
