# coding: utf-8

"""
    Paubox Email API

    Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paubox.models.error_response_errors_inner import ErrorResponseErrorsInner

class TestErrorResponseErrorsInner(unittest.TestCase):
    """ErrorResponseErrorsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorResponseErrorsInner:
        """Test ErrorResponseErrorsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorResponseErrorsInner`
        """
        model = ErrorResponseErrorsInner()
        if include_optional:
            return ErrorResponseErrorsInner(
                code = 56,
                title = '',
                details = ''
            )
        else:
            return ErrorResponseErrorsInner(
        )
        """

    def testErrorResponseErrorsInner(self):
        """Test ErrorResponseErrorsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
