# coding: utf-8

"""
    Paubox Email API

    Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paubox.api.dynamic_templates_api import DynamicTemplatesApi


class TestDynamicTemplatesApi(unittest.TestCase):
    """DynamicTemplatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DynamicTemplatesApi()

    def tearDown(self) -> None:
        pass

    def test_create_dynamic_template(self) -> None:
        """Test case for create_dynamic_template

        Create a dynamic template
        """
        pass

    def test_delete_dynamic_template(self) -> None:
        """Test case for delete_dynamic_template

        Delete a dynamic template
        """
        pass

    def test_get_dynamic_template(self) -> None:
        """Test case for get_dynamic_template

        Get a dynamic template
        """
        pass

    def test_list_dynamic_templates(self) -> None:
        """Test case for list_dynamic_templates

        List all dynamic templates
        """
        pass

    def test_send_templated_message(self) -> None:
        """Test case for send_templated_message

        Send a dynamically templated message
        """
        pass

    def test_update_dynamic_template(self) -> None:
        """Test case for update_dynamic_template

        Update a dynamic template
        """
        pass


if __name__ == '__main__':
    unittest.main()
