# coding: utf-8

"""
    Paubox Email API

    Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "paubox-python3"
VERSION = "2.0.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Paubox Email API",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Paubox Email API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Public documentation for Paubox&#39;s Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \&quot;Token token&#x3D;\&quot; prefix.  All requests must include the Authorization header in this exact format: &#x60;&#x60;&#x60; Authorization: Token token&#x3D;YOUR_API_KEY &#x60;&#x60;&#x60;  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \&quot;Token token&#x3D;\&quot; prefix, as most generators expect standard Bearer token format. 
    """,  # noqa: E501
    package_data={"paubox": ["py.typed"]},
)