# coding: utf-8

# flake8: noqa
"""
    Paubox Email API

    Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from paubox.models.attachment import Attachment
from paubox.models.bulk_send_request import BulkSendRequest
from paubox.models.bulk_send_request_data import BulkSendRequestData
from paubox.models.bulk_send_response import BulkSendResponse
from paubox.models.bulk_send_response_messages_inner import BulkSendResponseMessagesInner
from paubox.models.click_data import ClickData
from paubox.models.delete_dynamic_template200_response import DeleteDynamicTemplate200Response
from paubox.models.delivery_status import DeliveryStatus
from paubox.models.dynamic_template_list_response import DynamicTemplateListResponse
from paubox.models.dynamic_template_response import DynamicTemplateResponse
from paubox.models.error_response import ErrorResponse
from paubox.models.error_response_errors_inner import ErrorResponseErrorsInner
from paubox.models.message import Message
from paubox.models.message_content import MessageContent
from paubox.models.message_delivery import MessageDelivery
from paubox.models.message_headers import MessageHeaders
from paubox.models.message_receipt_error_response import MessageReceiptErrorResponse
from paubox.models.message_receipt_response import MessageReceiptResponse
from paubox.models.message_receipt_response_data import MessageReceiptResponseData
from paubox.models.message_receipt_response_data_message import MessageReceiptResponseDataMessage
from paubox.models.single_send_request import SingleSendRequest
from paubox.models.single_send_request_data import SingleSendRequestData
from paubox.models.single_send_response import SingleSendResponse
from paubox.models.templated_message import TemplatedMessage
from paubox.models.templated_message_headers import TemplatedMessageHeaders
from paubox.models.templated_message_request import TemplatedMessageRequest
from paubox.models.templated_message_request_data import TemplatedMessageRequestData

