# coding: utf-8

"""
    Paubox Email API

    Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DeliveryStatus(BaseModel):
    """
    DeliveryStatus
    """ # noqa: E501
    delivery_status: StrictStr = Field(description="The delivery status of the message", alias="deliveryStatus")
    delivery_time: Optional[StrictStr] = Field(default=None, description="The time when the message was delivered (if applicable)", alias="deliveryTime")
    opened_status: Optional[StrictStr] = Field(default=None, description="Whether the message was opened (single recipient only)", alias="openedStatus")
    opened_time: Optional[StrictStr] = Field(default=None, description="The time when the message was first opened (single recipient only)", alias="openedTime")
    __properties: ClassVar[List[str]] = ["deliveryStatus", "deliveryTime", "openedStatus", "openedTime"]

    @field_validator('delivery_status')
    def delivery_status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['processing', 'TLS not offered, sending via Secure Portal', 'soft bounced', 'soft bounced - mailbox full', 'hard bounced', 'Internal error. Please check back later.', 'delivered', 'delivered via secure portal']):
            raise ValueError("must be one of enum values ('processing', 'TLS not offered, sending via Secure Portal', 'soft bounced', 'soft bounced - mailbox full', 'hard bounced', 'Internal error. Please check back later.', 'delivered', 'delivered via secure portal')")
        return value

    @field_validator('opened_status')
    def opened_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['opened', 'not opened']):
            raise ValueError("must be one of enum values ('opened', 'not opened')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeliveryStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeliveryStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "deliveryStatus": obj.get("deliveryStatus"),
            "deliveryTime": obj.get("deliveryTime"),
            "openedStatus": obj.get("openedStatus"),
            "openedTime": obj.get("openedTime")
        })
        return _obj


