# coding: utf-8

"""
    Paubox Email API

    Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MessageHeaders(BaseModel):
    """
    MessageHeaders
    """ # noqa: E501
    subject: StrictStr
    var_from: StrictStr = Field(description="Must match the verified domain of your API key.", alias="from")
    reply_to: Optional[StrictStr] = Field(default=None, description="Reply-to address; must match a verified domain if different from from.", alias="reply-to")
    list_unsubscribe: Optional[StrictStr] = Field(default=None, description="Insert a List-Unsubscribe header (mailto and/or http). See RFC guidance for syntax. ", alias="List-Unsubscribe")
    list_unsubscribe_post: Optional[StrictStr] = Field(default=None, description="Used in conjunction with List-Unsubscribe header.", alias="List-Unsubscribe-Post")
    x_custom_header: Optional[StrictStr] = Field(default=None, description="Example custom header; any custom header may be added with an X- prefix.", alias="x-custom-header")
    additional_properties: Optional[StrictStr] = Field(default=None, description="Any additional X- prefixed custom header values.", alias="additionalProperties")
    __properties: ClassVar[List[str]] = ["subject", "from", "reply-to", "List-Unsubscribe", "List-Unsubscribe-Post", "x-custom-header", "additionalProperties"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MessageHeaders from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MessageHeaders from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "subject": obj.get("subject"),
            "from": obj.get("from"),
            "reply-to": obj.get("reply-to"),
            "List-Unsubscribe": obj.get("List-Unsubscribe"),
            "List-Unsubscribe-Post": obj.get("List-Unsubscribe-Post"),
            "x-custom-header": obj.get("x-custom-header"),
            "additionalProperties": obj.get("additionalProperties")
        })
        return _obj


