# coding: utf-8

"""
    Paubox Email API

    Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from paubox.models.click_data import ClickData
from paubox.models.message_delivery import MessageDelivery
from typing import Optional, Set
from typing_extensions import Self

class MessageReceiptResponseDataMessage(BaseModel):
    """
    MessageReceiptResponseDataMessage
    """ # noqa: E501
    id: StrictStr = Field(description="The message ID")
    message_deliveries: List[MessageDelivery]
    total_opens: Optional[StrictInt] = Field(default=None, description="Total number of opens (single recipient only)")
    distinct_opens: Optional[StrictInt] = Field(default=None, description="Number of distinct opens (single recipient only)")
    total_click_count: Optional[StrictInt] = Field(default=None, description="Total number of clicks (single recipient only)")
    clicks_per_link: Optional[List[ClickData]] = Field(default=None, description="Click tracking data per link (single recipient only)")
    unsubscribed: Optional[StrictBool] = Field(default=None, description="Whether the recipient has unsubscribed (single recipient only)")
    __properties: ClassVar[List[str]] = ["id", "message_deliveries", "total_opens", "distinct_opens", "total_click_count", "clicks_per_link", "unsubscribed"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MessageReceiptResponseDataMessage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in message_deliveries (list)
        _items = []
        if self.message_deliveries:
            for _item_message_deliveries in self.message_deliveries:
                if _item_message_deliveries:
                    _items.append(_item_message_deliveries.to_dict())
            _dict['message_deliveries'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in clicks_per_link (list)
        _items = []
        if self.clicks_per_link:
            for _item_clicks_per_link in self.clicks_per_link:
                if _item_clicks_per_link:
                    _items.append(_item_clicks_per_link.to_dict())
            _dict['clicks_per_link'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MessageReceiptResponseDataMessage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "message_deliveries": [MessageDelivery.from_dict(_item) for _item in obj["message_deliveries"]] if obj.get("message_deliveries") is not None else None,
            "total_opens": obj.get("total_opens"),
            "distinct_opens": obj.get("distinct_opens"),
            "total_click_count": obj.get("total_click_count"),
            "clicks_per_link": [ClickData.from_dict(_item) for _item in obj["clicks_per_link"]] if obj.get("clicks_per_link") is not None else None,
            "unsubscribed": obj.get("unsubscribed")
        })
        return _obj


