# coding: utf-8

# flake8: noqa

"""
    Paubox Email API

    Public documentation for Paubox's Transactional Email API  ## Authentication  **IMPORTANT**: This API uses a custom authentication format that requires the \"Token token=\" prefix.  All requests must include the Authorization header in this exact format: ``` Authorization: Token token=YOUR_API_KEY ```  **Note for Code Generation Tools**: Auto-generated code from this specification may need to be modified to include the \"Token token=\" prefix, as most generators expect standard Bearer token format. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "2.0.0"

# Define package exports
__all__ = [
    "DynamicTemplatesApi",
    "MessagesApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Attachment",
    "BulkSendRequest",
    "BulkSendRequestData",
    "BulkSendResponse",
    "BulkSendResponseMessagesInner",
    "ClickData",
    "DeleteDynamicTemplate200Response",
    "DeliveryStatus",
    "DynamicTemplateListResponse",
    "DynamicTemplateResponse",
    "ErrorResponse",
    "ErrorResponseErrorsInner",
    "Message",
    "MessageContent",
    "MessageDelivery",
    "MessageHeaders",
    "MessageReceiptErrorResponse",
    "MessageReceiptResponse",
    "MessageReceiptResponseData",
    "MessageReceiptResponseDataMessage",
    "SingleSendRequest",
    "SingleSendRequestData",
    "SingleSendResponse",
    "TemplatedMessage",
    "TemplatedMessageHeaders",
    "TemplatedMessageRequest",
    "TemplatedMessageRequestData",
]

# import apis into sdk package
from paubox.api.dynamic_templates_api import DynamicTemplatesApi as DynamicTemplatesApi
from paubox.api.messages_api import MessagesApi as MessagesApi

# import ApiClient
from paubox.api_response import ApiResponse as ApiResponse
from paubox.api_client import ApiClient as ApiClient
from paubox.configuration import Configuration as Configuration
from paubox.exceptions import OpenApiException as OpenApiException
from paubox.exceptions import ApiTypeError as ApiTypeError
from paubox.exceptions import ApiValueError as ApiValueError
from paubox.exceptions import ApiKeyError as ApiKeyError
from paubox.exceptions import ApiAttributeError as ApiAttributeError
from paubox.exceptions import ApiException as ApiException

# import models into sdk package
from paubox.models.attachment import Attachment as Attachment
from paubox.models.bulk_send_request import BulkSendRequest as BulkSendRequest
from paubox.models.bulk_send_request_data import BulkSendRequestData as BulkSendRequestData
from paubox.models.bulk_send_response import BulkSendResponse as BulkSendResponse
from paubox.models.bulk_send_response_messages_inner import BulkSendResponseMessagesInner as BulkSendResponseMessagesInner
from paubox.models.click_data import ClickData as ClickData
from paubox.models.delete_dynamic_template200_response import DeleteDynamicTemplate200Response as DeleteDynamicTemplate200Response
from paubox.models.delivery_status import DeliveryStatus as DeliveryStatus
from paubox.models.dynamic_template_list_response import DynamicTemplateListResponse as DynamicTemplateListResponse
from paubox.models.dynamic_template_response import DynamicTemplateResponse as DynamicTemplateResponse
from paubox.models.error_response import ErrorResponse as ErrorResponse
from paubox.models.error_response_errors_inner import ErrorResponseErrorsInner as ErrorResponseErrorsInner
from paubox.models.message import Message as Message
from paubox.models.message_content import MessageContent as MessageContent
from paubox.models.message_delivery import MessageDelivery as MessageDelivery
from paubox.models.message_headers import MessageHeaders as MessageHeaders
from paubox.models.message_receipt_error_response import MessageReceiptErrorResponse as MessageReceiptErrorResponse
from paubox.models.message_receipt_response import MessageReceiptResponse as MessageReceiptResponse
from paubox.models.message_receipt_response_data import MessageReceiptResponseData as MessageReceiptResponseData
from paubox.models.message_receipt_response_data_message import MessageReceiptResponseDataMessage as MessageReceiptResponseDataMessage
from paubox.models.single_send_request import SingleSendRequest as SingleSendRequest
from paubox.models.single_send_request_data import SingleSendRequestData as SingleSendRequestData
from paubox.models.single_send_response import SingleSendResponse as SingleSendResponse
from paubox.models.templated_message import TemplatedMessage as TemplatedMessage
from paubox.models.templated_message_headers import TemplatedMessageHeaders as TemplatedMessageHeaders
from paubox.models.templated_message_request import TemplatedMessageRequest as TemplatedMessageRequest
from paubox.models.templated_message_request_data import TemplatedMessageRequestData as TemplatedMessageRequestData

